name: mapbox_gl
description: A Flutter plugin for integrating Mapbox Maps SDK inside a Flutter widget in iOS and Android applications.
version: 0.0.3
authors:
  - Mapbox <tobrun@mapbox.com>
  - TopHap <home@long1.eu>
homepage: https://github.com/tobrun/flutter-mapbox-gl

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.mapbox.mapboxgl
    pluginClass: MapboxMapsPlugin